# Generated by Django 5.2.3 on 2026-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_upvotes_supportticketupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
