# Generated by Django 5.2.3 on 2026-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
