# Generated by Django 5.2.3 on 2026-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='labels',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
