"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# CRITICAL: In production, SECRET_KEY MUST be set via environment variable
# NEVER use the default value in production environments
if 'SECRET_KEY' not in os.environ:
    import warnings
    warnings.warn(
        'SECRET_KEY is not set via environment variable. Using development default. '
        'Set SECRET_KEY environment variable in production!',
        RuntimeWarning
    )

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-key-only-for-development-use-env-var-in-production'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Development default: keep DEBUG enabled while building locally.
# IMPORTANT: Set DEBUG = False in production to prevent information disclosure.
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# Default to local-safe hosts in development; override via env in deployment.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1'
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps for IT Service Desk
    'tickets',
    'ai_engine',
    'dashboard',
    'monitoring',
    'users.apps.UsersConfig',
    'support.apps.SupportConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom security middleware for rate limiting and security headers
    'config.security_middleware.RateLimitMiddleware',
    'config.security_middleware.SecurityHeadersMiddleware',
    'config.security_middleware.InputValidationMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Template configuration
# DIRS: Add project-level templates directory
# APP_DIRS: True allows Django to look for templates in each app's templates folder
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================
# Used for rate limiting and session storage
# Configurable based on environment - local dev uses in-memory, production uses Redis
if os.getenv('REDIS_URL'):
    # Production: use Redis for shared cache across processes
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            }
        }
    }
else:
    # Development: use in-memory cache (not suitable for multi-process)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'itdesk-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }

# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# Enhanced security settings for production
SESSION_COOKIE_SECURE = not DEBUG  # Only send HTTPS in production
SESSION_COOKIE_HTTPONLY = True     # Prevent JavaScript access
CSRF_COOKIE_SECURE = not DEBUG     # Only send HTTPS in production
# CSRF_COOKIE_HTTPONLY = False is required when using {% csrf_token %} template tag
# which is used throughout this application (not False by default in Django)
CSRF_COOKIE_HTTPONLY = False       # Allow {% csrf_token %} template tag to work
# Normalize CSRF_TRUSTED_ORIGINS: split on comma and strip whitespace from each origin
csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in csrf_origins_str.split(',') 
    if origin.strip()
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'error.log',
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'info.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'tickets': {
            'handlers': ['file', 'info_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'support': {
            'handlers': ['file', 'info_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'ai_engine': {
            'handlers': ['file', 'info_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'
