# Generated by Django 5.2.11 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
