# Generated by Django 5.2.11 on 2026-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='suggested_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
