# Generated by Django 5.2.11 on 2026-04-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticket_suggested_solution"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ai_action_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_feedback_text",
            field=models.TextField(
                blank=True, help_text="User's feedback on the AI suggestion"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_solution_helpful",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True=helpful, False=not helpful, None=not yet reviewed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_by_ai",
            field=models.BooleanField(
                default=False, help_text="Whether the AI solution resolved the issue"
            ),
        ),
    ]
